{
 "title": "Prometheus: OpenNMS Core Internals",
 "description": "Monitoring of internal JMX metrics from the OpenNMS Core system collected via JMX exporter for Prometheus.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheusDS", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"jmx_core\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Completion Ratio",
   "type": "stat",
   "description": "Pollerd completion ratio in percent. Should be 100.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_pollerd_taskcompletionratio",
     "legendFormat": "polled"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "timeseries",
   "description": "Pollerd thread usage statistics ",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opennms_pollerd_activethreads{instance=\"$instance\"}",
     "legendFormat": "active"
    },
    {
     "expr": "opennms_pollerd_corepoolthreads{instance=\"$instance\"}",
     "legendFormat": "pool size"
    },
    {
     "expr": "opennms_pollerd_numpollsinflight",
     "legendFormat": "in flight"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "timeseries",
   "description": "Pollerd scheduler task statistics",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opennms_pollerd_taskqueuependingcount{instance=\"$instance\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "opennms_pollerd_taskcompletionratio",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "description": "Polling tasks in pending queue. Should be 0.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_pollerd_taskqueuependingcount",
     "legendFormat": "polled"
    }
   ]
  },
  {
   "title": "Polling Rate",
   "type": "stat",
   "description": "Polls per second over a 1 minute time window.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(opennms_pollerd_numpolls{instance=\"$instance\"}[1m])",
     "legendFormat": "polled"
    }
   ]
  },
  { "title": "Metric Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Completion Ratio",
   "type": "stat",
   "description": "Collectd completion ratio in percent. Should be 100.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_collectd_taskcompletionratio",
     "legendFormat": "polled"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "timeseries",
   "description": "Collectd thread usage statistics ",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opennms_collectd_activethreads{instance=\"$instance\"}",
     "legendFormat": "active"
    },
    {
     "expr": "opennms_collectd_maxpoolthreads{instance=\"$instance\"}",
     "legendFormat": "pool size"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "timeseries",
   "description": "Collectd scheduler task statistics",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opennms_collectd_taskqueuependingcount{instance=\"$instance\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "opennms_collectd_taskcompletionratio",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "description": "Collection tasks in pending queue. Should be 0.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_collectd_taskqueuependingcount",
     "legendFormat": "polled"
    }
   ]
  },
  {
   "title": "Collectible Services",
   "type": "stat",
   "description": "Number of services we collect metrics from.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennms_collectd_collectableservicecount",
     "legendFormat": "polled"
    }
   ]
  },
  { "title": "Event Daemon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Event Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_oneminuterate",
     "legendFormat": "1 minute"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_fiveminuterate",
     "legendFormat": "5 minutes"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_fifteenminuterate",
     "legendFormat": "15 minutes"
    }
   ]
  },
  {
   "title": "Event Broadcast Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_oneminuterate",
     "legendFormat": "1 minute"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_fiveminuterate",
     "legendFormat": "5 minutes"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_fifteenminuterate",
     "legendFormat": "15 minutes"
    }
   ]
  },
  {
   "title": "Event Expansion Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_oneminuterate",
     "legendFormat": "1 minute"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_fiveminuterate",
     "legendFormat": "5 minutes"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_fifteenminuterate",
     "legendFormat": "15 minutes"
    }
   ]
  },
  {
   "title": "Event Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_oneminuterate",
     "legendFormat": "1 minute"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_fiveminuterate",
     "legendFormat": "5 minutes"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_fifteenminuterate",
     "legendFormat": "15 minutes"
    }
   ]
  },
  {
   "title": "Event Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_999thpercentile",
     "legendFormat": "99.9th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_99thpercentile",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_98thpercentile",
     "legendFormat": "98th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_95thpercentile",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_75thpercentile",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_50thpercentile",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Event Broadcast Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_999thpercentile",
     "legendFormat": "99.9th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_99thpercentile",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_98thpercentile",
     "legendFormat": "98th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_95thpercentile",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_75thpercentile",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_broadcast_50thpercentile",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Event Expansion Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_999thpercentile",
     "legendFormat": "99.9th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_99thpercentile",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_98thpercentile",
     "legendFormat": "98th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_95thpercentile",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_75thpercentile",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_expand_50thpercentile",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Event Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_999thpercentile",
     "legendFormat": "99.9th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_99thpercentile",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_98thpercentile",
     "legendFormat": "98th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_95thpercentile",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_75thpercentile",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "org_opennms_netmgt_eventd_eventlogs_process_write_50thpercentile",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Provisioning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Import Thread Pool",
     "type": "timeseries",
     "description": "Provisiond import thread usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_importactivethreads{instance=\"$instance\"}",
       "legendFormat": "import active"
      },
      {
       "expr": "opennms_provisiond_importcorepoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Writer Thread Pool",
     "type": "timeseries",
     "description": "Provisiond writer thread usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_writeactivethreads{instance=\"$instance\"}",
       "legendFormat": "writer active"
      },
      {
       "expr": "opennms_provisiond_writecorepoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Scan Thread Pool",
     "type": "timeseries",
     "description": "Provisiond scan thread usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_scanactivethreads{instance=\"$instance\"}",
       "legendFormat": "scan active"
      },
      {
       "expr": "opennms_provisiond_scancorepoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Scheduler Thread Pool",
     "type": "timeseries",
     "description": "Provisiond scheduler thread usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_scheduledactivethreads{instance=\"$instance\"}",
       "legendFormat": "scheduler active"
      },
      {
       "expr": "opennms_provisiond_scheduledcorepoolthreads{instance=\"$instance\"}",
       "legendFormat": "pool size"
      }
     ]
    },
    {
     "title": "Import Scheduler",
     "type": "timeseries",
     "description": "Provisiond import scheduler usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_importtaskqueuependingcount{instance=\"$instance\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "rate(opennms_provisiond_importtaskscompleted{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "opennms_provisiond_importtaskcompletionratio{instance=\"$instance\"}",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Writer Scheduler",
     "type": "timeseries",
     "description": "Provisiond writer scheduler usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_writetaskqueuependingcount{instance=\"$instance\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "rate(opennms_provisiond_writetaskscompleted{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "opennms_provisiond_writetaskcompletionratio{instance=\"$instance\"}",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Scan Scheduler",
     "type": "timeseries",
     "description": "Provisiond scan scheduler usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "opennms_provisiond_scantaskqueuependingcount{instance=\"$instance\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "rate(opennms_provisiond_scantaskscompleted{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "opennms_provisiond_scantaskcompletionratio{instance=\"$instance\"}",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Scheduler",
     "type": "timeseries",
     "description": "Provisiond scheduler usage statistics ",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(opennms_provisiond_scheduledtaskqueuependingcount{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "pending"
      },
      {
       "expr": "rate(opennms_provisiond_scheduledtaskscompleted{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "opennms_provisiond_scheduledtaskcompletionratio{instance=\"$instance\"}",
       "legendFormat": "ratio"
      }
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_pool_opennms_activeconnections",
     "legendFormat": "active"
    },
    {
     "expr": "com_zaxxer_hikari_pool_opennms_idleconnections",
     "legendFormat": "idle"
    },
    {
     "expr": "com_zaxxer_hikari_pool_opennms_threadsawaitingconnection",
     "legendFormat": "threads waiting"
    },
    {
     "expr": "com_zaxxer_hikari_poolconfig_opennms_maximumpoolsize",
     "legendFormat": "pool size"
    }
   ]
  },
  {
   "title": "SNMP Trap Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNMP Trap Reception",
     "type": "timeseries",
     "description": "Statistics about received SNMP Traps and their versions processed by the OpenNMS Core system.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(opennms_trapd_v1trapsreceived{instance =~ \"$instance\"}[1m])",
       "legendFormat": "v1"
      },
      {
       "expr": "rate(opennms_trapd_v2ctrapsreceived{instance =~ \"$instance\"}[1m])",
       "legendFormat": "v2c"
      },
      {
       "expr": "rate(opennms_trapd_v3trapsreceived{instance =~ \"$instance\"}[1m])",
       "legendFormat": "v3"
      },
      {
       "expr": "rate(opennms_trapd_vunknowntrapsreceived{instance =~ \"$instance\"}[1m])",
       "legendFormat": "unknown"
      }
     ]
    },
    {
     "title": "SNMP Trap Failures",
     "type": "timeseries",
     "description": "Statistics about SNMP trap reception failures. ",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(opennms_trapd_trapsdiscarded{instance=~\"$instance\"}[1m])",
       "legendFormat": "discarded"
      },
      {
       "expr": "rate(opennms_trapd_trapserrored{instance=~\"$instance\"}[1m])",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "SNMP Trap IPC Consumer Dispatch",
     "type": "timeseries",
     "description": "Statistics about IPC consumer dispatch time for SNMP Traps internally",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_consumer_trap_dispatchtime_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      }
     ]
    },
    {
     "title": "SNMP Trap IPC Producer Dispatch",
     "type": "timeseries",
     "description": "Statistics about IPC producer dispatch time for SNMP Traps internally",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_core_ipc_sink_producer_trap_dispatchtime_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Syslog Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syslog conversation ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "rate(org_opennms_netmgt_syslogd_consumer_toevent_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "syslog to event"
      }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Adapter: NetFlow v5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "NetFlow v5 Reception Statistics",
     "type": "timeseries",
     "description": "Statistics about reception of NetFlow v5 messages on Telemetryd adapter.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_entriesreceived_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "received"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_entriesparsed_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "parsed"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_entriesconverted_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "converted"
      },
      {
       "expr": "rate(org_opennms_core_ipc_sink_consumer_telemetry_netflow_5_dropped_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "dropped"
      }
     ]
    },
    {
     "title": "NetFlow v5 Log Parser Latency",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_logparsing_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_logparsing_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_logparsing_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_logparsing_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_logparsing_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_logparsing_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      }
     ]
    },
    {
     "title": "NetFlow v5 Packets per Log",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_5_netflow_5_adapter_packetsperlog_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters__netflow_5_netflow_5_adapter_packetsperlog_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters__netflow_5_netflow_5_adapter_packetsperlog_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters__netflow_5_netflow_5_adapter_packetsperlog_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters__netflow_5_netflow_5_adapter_packetsperlog_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters__netflow_5_netflow_5_adapter_packetsperlog_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Adapter: NetFlow v9",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "NetFlow v9 Reception Statistics",
     "type": "timeseries",
     "description": "Statistics about reception of NetFlow v9 messages on Telemetryd adapter.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_entriesreceived_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "received"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_entriesparsed_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "parsed"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_entriesconverted_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "converted"
      },
      {
       "expr": "rate(org_opennms_core_ipc_sink_consumer_telemetry_netflow_9_dropped_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "dropped"
      }
     ]
    },
    {
     "title": "NetFlow v9 Log Parser Latency",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_logparsing_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_logparsing_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_logparsing_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_logparsing_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_logparsing_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_logparsing_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      }
     ]
    },
    {
     "title": "NetFlow v9 Packets per Log",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_packetsperlog_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_packetsperlog_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_packetsperlog_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_packetsperlog_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_packetsperlog_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_netflow_9_netflow_9_adapter_packetsperlog_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Adapter: IPFIX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPFIX Reception Statistics",
     "type": "timeseries",
     "description": "Statistics about reception of IPFIX (NetFlow v10) messages on Telemetryd adapter.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_entriesreceived_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "received"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_entriesparsed_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "parsed"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_entriesconverted_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "converted"
      },
      {
       "expr": "rate(org_opennms_core_ipc_sink_consumer_telemetry_ipfix_dropped_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "dropped"
      }
     ]
    },
    {
     "title": "IPFIX Log Parser Latency",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_logparsing_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_logparsing_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_logparsing_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_logparsing_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_logparsing_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_logparsing_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      }
     ]
    },
    {
     "title": "IPFIX Packets per Log",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_packetsperlog_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_packetsperlog_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_packetsperlog_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_packetsperlog_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_packetsperlog_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_ipfix_ipfix_adapter_packetsperlog_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Adapter: sFlow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "sFlow Reception Statistics",
     "type": "timeseries",
     "description": "Statistics about reception of sFlow messages on Telemetryd adapter.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_entriesreceived_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "received"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_entriesparsed_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "parsed"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_entriesconverted_count{instance =~\"$instance\"}[1m])",
       "legendFormat": "converted"
      },
      {
       "expr": "rate(org_opennms_core_ipc_sink_consumer_telemetry_sflow_dropped_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "dropped"
      }
     ]
    },
    {
     "title": "sFlow Log parsing statistics",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_logparsing_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_logparsing_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_logparsing_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_logparsing_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_logparsing_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_logparsing_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      }
     ]
    },
    {
     "title": "sFlow Packets per Log",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_packetsperlog_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_packetsperlog_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_packetsperlog_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_packetsperlog_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_packetsperlog_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_sflow_sflow_adapter_packetsperlog_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Adapter: BMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "BMP Reception Statistics",
     "type": "timeseries",
     "description": "Statistics about reception of BMP messages on Telemetryd adapter.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_logparsing_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "parsed"
      },
      {
       "expr": "rate(org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_recordsconsumed_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "consumed"
      }
     ]
    },
    {
     "title": "BMP Log parsing statistics",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_logparsing_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_logparsing_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_logparsing_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_logparsing_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_logparsing_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_logparsing_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      }
     ]
    },
    {
     "title": "BMP Packets per Log",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_packetsperlog_999thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99.9th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_packetsperlog_99thpercentile{instance=~\"$instance\"}",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_packetsperlog_98thpercentile{instance=~\"$instance\"}",
       "legendFormat": "98th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_packetsperlog_95thpercentile{instance=~\"$instance\"}",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_packetsperlog_75thpercentile{instance=~\"$instance\"}",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "org_opennms_netmgt_telemetry_adapters_bmp_bmp_peer_status_adapter_packetsperlog_50thpercentile{instance=~\"$instance\"}",
       "legendFormat": "50th percentile"
      }
     ]
    }
   ]
  }
 ]
}